module I18n
  module Env
    class Config < I18n::Config
      VERSION: String
      VARS: ::Array[String]

      def locale: () -> untyped

      private

      def find_user_locale: () -> untyped
      def find_primary: () -> untyped
      def find_secondary: () -> untyped
      def locales: () -> untyped
      def normalize: (untyped lang) -> untyped
    end
  end
end
