module I18n
  module Env
    class Config < I18n::Config
      VERSION: String
      VARS: Array[String]

      @locales: Array[Symbol]
      @locale: Symbol

      def locale: () -> Symbol

      private

      def find_user_locale: () -> Symbol?
      def find_primary: () -> Symbol?
      def find_secondary: () -> Symbol?
      def locales: () -> Array[Symbol]
      def normalize: (String lang) -> Symbol
    end
  end
end
