interface _ResolverClass
  def new: (config config) -> void
end
interface _Resolver
  def initialize: (config config) -> void
  def resolve: (Buchungsstreber::Entry) -> void
end

class Buchungsstreber::Resolver
  @resolvers: Array[_Resolver]
  @config: config

  def initialize: (config config) -> void

  def resolve: (Buchungsstreber::Entry entry) -> Buchungsstreber::Entry
  def load!: (String name) -> void

  private

  def resolver: (String klass) -> _Resolver

  module Base
    @resolvers: Array[_Resolver]

    def self.included: (_ResolverClass klass) -> void
    def self.resolver: (String name) -> _Resolver?
  end
end
