class Buchungsstreber::Resolver::Redmines
  include Buchungsstreber::Resolver::Base

  @redmines: Buchungsstreber::Redmines

  def initialize: (Array[config] config) -> void
  def resolve: (entry entry) -> void
end
