class Buchungsstreber::Resolver::Templates
  include Buchungsstreber::Resolver::Base

  @templates: template_config

  def initialize: (config config) -> void
  def resolve: (entry entry) -> void
end
