class Buchungsstreber::YamlTimesheet
  include Buchungsstreber::TimesheetParser::Base
  include Buchungsstreber::TimesheetParser::LineBased
  include _Parser

  @file_path: String
  @templates: Hash[untyped, untyped]
  @minimum_time: Float

  def self.parses?: (String file) -> bool

  private

  def format_entry: (entry e) -> String
  def format_day: (Date d) -> ::String
end
